name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI-Temperatura:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker images

        uses: docker/build-push-action@v2.10.0
        with:
            context: ./src
            file: ./src/Dockerfile
            push: true 
            tags: |
              ericosa/conversao-temperatura:latest
              ericosa/conversao-temperatura:${{ github.run_number }}
  CD-Temperatura:
    needs: [CI-Temperatura]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with: 
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.0
        with:
          images: ericosa/conversao-temperatura:${{ github.run_number }}
          manifests : |
            k8s/deployment.yaml
